package com.wtz.tools.utils.network.socket.test;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    java.util.List<Person.PhoneNumber>
        getPhoneList();
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    Person.PhoneNumber getPhone(int index);
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    int getPhoneCount();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
      email_ = "";
      phone_ = emptyProtobufList();
    }
    /**
     * Protobuf enum {@code Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Person.PhoneNumber)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      PhoneType getType();
    }
    /**
     * Protobuf type {@code Person.PhoneNumber}
     */
    public  static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageLite<
            PhoneNumber, PhoneNumber.Builder> implements
        // @@protoc_insertion_point(message_implements:Person.PhoneNumber)
        PhoneNumberOrBuilder {
      private PhoneNumber() {
        number_ = "";
        type_ = 1;
      }
      private int bitField0_;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private String number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public String getNumber() {
        return number_;
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(number_);
      }
      /**
       * <code>required string number = 1;</code>
       */
      private void setNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
      }
      /**
       * <code>required string number = 1;</code>
       */
      private void clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
      }
      /**
       * <code>required string number = 1;</code>
       */
      private void setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value.toStringUtf8();
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      public PhoneType getType() {
        PhoneType result = PhoneType.forNumber(type_);
        return result == null ? PhoneType.HOME : result;
      }
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      private void setType(PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
      }
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      private void clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeString(1, getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      public static PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            PhoneNumber, Builder> implements
          // @@protoc_insertion_point(builder_implements:Person.PhoneNumber)
          PhoneNumberOrBuilder {
        // Construct using PersonProtos.Person.PhoneNumber.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return instance.hasNumber();
        }
        /**
         * <code>required string number = 1;</code>
         */
        public String getNumber() {
          return instance.getNumber();
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          return instance.getNumberBytes();
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            String value) {
          copyOnWrite();
          instance.setNumber(value);
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          copyOnWrite();
          instance.clearNumber();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setNumberBytes(value);
          return this;
        }

        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return instance.hasType();
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public PhoneType getType() {
          return instance.getType();
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(PhoneType value) {
          copyOnWrite();
          instance.setType(value);
          return this;
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          copyOnWrite();
          instance.clearType();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
      }
      private byte memoizedIsInitialized = -1;
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new PhoneNumber();
          }
          case IS_INITIALIZED: {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return DEFAULT_INSTANCE;
            if (isInitialized == 0) return null;

            boolean shouldMemoize = ((Boolean) arg0).booleanValue();
            if (!hasNumber()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
            if (shouldMemoize) memoizedIsInitialized = 1;
            return DEFAULT_INSTANCE;

          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            PhoneNumber other = (PhoneNumber) arg1;
            number_ = visitor.visitString(
                hasNumber(), number_,
                other.hasNumber(), other.number_);
            type_ = visitor.visitInt(hasType(), type_,
                other.hasType(), other.type_);
            if (visitor == MergeFromVisitor
                .INSTANCE) {
              bitField0_ |= other.bitField0_;
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!parseUnknownField(tag, input)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readString();
                    bitField0_ |= 0x00000001;
                    number_ = s;
                    break;
                  }
                  case 16: {
                    int rawValue = input.readEnum();
                    PhoneType value = PhoneType.forNumber(rawValue);
                    if (value == null) {
                      super.mergeVarintField(2, rawValue);
                    } else {
                      bitField0_ |= 0x00000002;
                      type_ = rawValue;
                    }
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (PhoneNumber.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:Person.PhoneNumber)
      private static final PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PhoneNumber();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<PhoneNumber> PARSER;

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>required string name = 1;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
    }
    /**
     * <code>required string name = 1;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>required string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value.toStringUtf8();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    private void setId(int value) {
      bitField0_ |= 0x00000002;
      id_ = value;
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    private void clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private String email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    private void setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      email_ = value;
    }
    /**
     * <code>optional string email = 3;</code>
     */
    private void clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 3;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      email_ = value.toStringUtf8();
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<PhoneNumber> phone_;
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<PhoneNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<? extends PhoneNumberOrBuilder>
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }
    private void ensurePhoneIsMutable() {
      if (!phone_.isModifiable()) {
        phone_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(phone_);
       }
    }

    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void setPhone(
        int index, PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhoneIsMutable();
      phone_.set(index, value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void setPhone(
        int index, PhoneNumber.Builder builderForValue) {
      ensurePhoneIsMutable();
      phone_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void addPhone(PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhoneIsMutable();
      phone_.add(value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void addPhone(
        int index, PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhoneIsMutable();
      phone_.add(index, value);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void addPhone(
        PhoneNumber.Builder builderForValue) {
      ensurePhoneIsMutable();
      phone_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void addPhone(
        int index, PhoneNumber.Builder builderForValue) {
      ensurePhoneIsMutable();
      phone_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void addAllPhone(
        Iterable<? extends PhoneNumber> values) {
      ensurePhoneIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, phone_);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void clearPhone() {
      phone_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    private void removePhone(int index) {
      ensurePhoneIsMutable();
      phone_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getEmail());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(4, phone_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getEmail());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phone_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        PersonOrBuilder {
      // Construct using PersonProtos.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return instance.hasEmail();
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public java.util.List<PhoneNumber> getPhoneList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhoneList());
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public int getPhoneCount() {
        return instance.getPhoneCount();
      }/**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumber getPhone(int index) {
        return instance.getPhone(index);
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
          int index, PhoneNumber value) {
        copyOnWrite();
        instance.setPhone(index, value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
          int index, PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setPhone(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(PhoneNumber value) {
        copyOnWrite();
        instance.addPhone(value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          int index, PhoneNumber value) {
        copyOnWrite();
        instance.addPhone(index, value);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhone(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          int index, PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhone(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addAllPhone(
          Iterable<? extends PhoneNumber> values) {
        copyOnWrite();
        instance.addAllPhone(values);
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder removePhone(int index) {
        copyOnWrite();
        instance.removePhone(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Person();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasName()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getPhoneCount(); i++) {
            if (!getPhone(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          phone_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Person other = (Person) arg1;
          name_ = visitor.visitString(
              hasName(), name_,
              other.hasName(), other.name_);
          id_ = visitor.visitInt(
              hasId(), id_,
              other.hasId(), other.id_);
          email_ = visitor.visitString(
              hasEmail(), email_,
              other.hasEmail(), other.email_);
          phone_= visitor.visitList(phone_, other.phone_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  name_ = s;
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  id_ = input.readInt32();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  email_ = s;
                  break;
                }
                case 34: {
                  if (!phone_.isModifiable()) {
                    phone_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(phone_);
                  }
                  phone_.add(
                      input.readMessage(PhoneNumber.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Person.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Person)
    private static final Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
